Ticket-8
yuridevweb/News-API pull request #8
Opened 2022-03-29 15:40 UTC by yuridevweb

2022-03-30 10:49 UTC, giteron requested changes
Nice inventive way of adding comment counts! However, this could be done with a single database query. This would help the efficiency of your getArticles function, especially if it had a large data set to work with (e.g. 100s-1000s of articles).

You have most of the syntax for generating a comment count, so it should just be a case of combining the two requests :)

2022-03-31 09:34 UTC, jadelandeg commented on __tests__/app.test.js
>                body: expect.any(String),
check the trello for what we expect in this endpoint, don't want to see the body when getting all articles.

2022-03-31 09:38 UTC, jadelandeg commented on controllers/news.controllers.js
> +          article.comment_count = Number(results[index].count)
should be doing get articles with comment count in one query here, not using a promise.all. Shouldn't use the length, should take advantage of SQL functions.

2022-03-31 09:42 UTC, jadelandeg commented on models/news.models.js
> +  return db.query(queryStr).then((result) => {
looking great!

2022-03-31 09:42 UTC, jadelandeg commented on models/news.models.js
> +  return db.query(queryStr).then((result) => {
just a minor change to stop the body coming back

2022-03-31 09:42 UTC, jadelandeg requested changes
Good job, Yuri! Just a little change this time. Make sure the query is returning the keys listed on the trello ticket :)

2022-03-31 10:52 UTC, cavalierswain commented
Good effort on implementing the changes!
looks good!

2022-03-31 11:11 UTC, merged